apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-envmanager-backend
  namespace: {{ .Release.namespace }}
  labels:
    operator-controller: phoenix-envmanager-backend
    app.kubernetes.io/name: phoenix-backend
spec:
  {{- if not .Values.phoenixBackend.autoscaling.enabled }}
    replicas: {{ .Values.phoenixBackend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      operator-controller: phoenix-envmanager-backend
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: phoenix-backend
      labels:
        operator-controller: phoenix-envmanager-backend
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /app
        - -dsn=host=phoenix-backend-db.operators.svc.cluster.local port=5432 user=postgres password=postgres dbname=env_manager timezone=UTC connect_timeout=5
        name: {{ .Values.phoenixBackend.containerName }}
        image: "{{ .Values.phoenixBackend.image.repository }}:{{ .Values.phoenixBackend.image.tag }}"
        ports:
          - containerPort: {{ .Values.phoenixBackend.container.port }}
        imagePullPolicy: {{ .Values.phoenixBackend.image.pullPolicy }}
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: {{ .Values.phoenixBackend.serviceAccount.name }}
      terminationGracePeriodSeconds: 10