apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.phoenixDB.volumes.storageClassName }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.phoenixDB.volumes.fileSystemId }}
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.phoenixDB.volumes.claimName }}
  namespace: {{ .Release.namespace }}
  labels:
    operator-controller: phoenix-envmanager-backend-db
    app.kubernetes.io/name: phoenix-backend-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.phoenixDB.volumes.storageClassName }}
  resources:
    requests:
      storage: 2Gi